# Generated by Django 6.0.5 on 2026-09-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['chapter_number']},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='content_images_folder',
        ),
        migrations.AddField(
            model_name='chapter',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Бичвэр эсвэл Агуулга'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Аниме бичлэгийн линк (YouTube/Drive)'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.IntegerField(default=1, verbose_name='Ангийн дугаар'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Бүлгийн нэр / Дугаар'),
        ),
    ]
